inherit_from: configs/Replica/replica.yaml
mode: rgbd
mapping:
  bound: [[-5.0, 5.0], [-5.0, 5.0], [-5.0, 5.0]]
meshing:
  gt_mesh_path: /home/yzhang/data/Replica/cull_replica_meshv2/office4.ply
data:
  input_folder: /home/skz/cs231n/GO-SLAM-skz/datasets/Replica/office4
  output: /home/skz/cs231n/GO-SLAM-skz/out/replica/office4/rgbd
