inherit_from: configs/Replica/replica_mono.yaml
mode: mono
mapping:
  bound: [[-2.0, 2.0], [-2.0, 2.0], [-2.0, 2.0]]
meshing:
  gt_mesh_path: /home/yzhang/data/Replica/cull_replica_meshv2/office3.ply
data:
  input_folder: /home/skz/cs231n/GO-SLAM-skz/datasets/Replica/office3
  output:/home/skz/cs231n/GO-SLAM-skz/out/replica/office3/mono
