inherit_from: configs/Replica/replica.yaml
mode: rgbd
mapping:
  bound: [[-5.0, 5.0], [-5.0, 5.0], [-5.0, 5.0]]
meshing:
  gt_mesh_path: /home/skz/GO-SLAM-skz/datasets/Replica/cull_replica_meshv2/office3.ply
data:
  input_folder: /home/skz/cs231n/GO-SLAM-skz/datasets/Replica/office3
  output: /home/skz/cs231n/GO-SLAM-skz/out/replica/office3/rgbd
