inherit_from: configs/Replica/replica_mono.yaml
mode: mono
mapping:
  bound: [[-2.0, 2.0], [-2.0, 2.0], [-2.0, 2.0]]
meshing:
  gt_mesh_path: /home/skz/GO-SLAM-skz/datasets/Replica/cull_replica_meshv2/room2.ply
data:
  input_folder: /home/skz/cs231n/GO-SLAM-skz/datasets/Replica/room2
  output: /home/skz/cs231n/GO-SLAM-skz/out/replica/room2/mono
